import Provider from "@/components/Provider";
import { Lexend } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Menu from "@/components/Menu";
import NickNameModal from "@/components/NickNameModal";

// Others

const inter = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Predix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${inter.className} overscroll-none bg-[--colors-backgroundAlt]`}
      >
        <Provider>
          <Header />
          <NickNameModal />
          {children}
          <Footer />
          <Menu />
        </Provider>
      </body>
    </html>
  );
}
